const {
  snacks,
  pantry,
  candy,
  beverages,
  meatAndSeafood,
  bakeryAndDessert,
  breakfast,
  cleaning,
  coffee,
  deli,
  floral,
  household,
  organic,
} = require('./DTO');

const users = [
  {
    name: 'Admin',
    email: 'admin@email.com',
    password: 'password',
    role: 'admin',
  },
  {
    name: 'User',
    email: 'user@email.com',
    password: 'password',
    role: 'user',
  },
];

const customers = [
  {
    id: '8740c842-16af-4f9f-a19e-f3b8c8c11eef',
    name: 'Delba de Oliveira',
    email: 'delba@oliveira.com',
    image_url: '/customers/delba-de-oliveira.png',
  },
  {
    id: '6ee9e3d2-59df-4663-aa15-ff9631ca4fcb',
    name: 'Lee Robinson',
    email: 'lee@robinson.com',
    image_url: '/customers/lee-robinson.png',
  },
  {
    id: '6e2c99aa-5d20-4471-8cab-1f00c8ade6ac',
    name: 'Hector Simpson',
    email: 'hector@simpson.com',
    image_url: '/customers/hector-simpson.png',
  },
  {
    id: 'e6c54737-5101-415a-a02b-accaa7bff144',
    name: 'Steven Tey',
    email: 'steven@tey.com',
    image_url: '/customers/steven-tey.png',
  },
  {
    id: '2afd24b1-3c3e-4a86-89b8-0330baced415',
    name: 'Steph Dietz',
    email: 'steph@dietz.com',
    image_url: '/customers/steph-dietz.png',
  },
  {
    id: '8310bea2-c75b-4fd9-ad3b-7431188b1eee',
    name: 'Michael Novotny',
    email: 'michael@novotny.com',
    image_url: '/customers/michael-novotny.png',
  },
  {
    id: 'a261ede5-9109-468f-9715-394e85f0cce0',
    name: 'Evil Rabbit',
    email: 'evil@rabbit.com',
    image_url: '/customers/evil-rabbit.png',
  },
  {
    id: '7fd66d00-df0b-43ea-a141-8ce4008c0e63',
    name: 'Emil Kowalski',
    email: 'emil@kowalski.com',
    image_url: '/customers/emil-kowalski.png',
  },
  {
    id: '67a29fb8-4b85-487b-ab82-11632718c5db',
    name: 'Amy Burns',
    email: 'amy@burns.com',
    image_url: '/customers/amy-burns.png',
  },
  {
    id: '6de2e243-e8af-41e9-bff1-9095ce1e1d00',
    name: 'Balazs Orban',
    email: 'balazs@orban.com',
    image_url: '/customers/balazs-orban.png',
  },
];

const orders = [
  {
    customer_id: customers[0].id,
    product_id: snacks[0].id,
    quantity: Math.floor(snacks[0].stock / 3),
    status: 'pending',
    date: '2023-11-06',
  },
  {
    customer_id: customers[1].id,
    product_id: pantry[0].id,
    quantity: Math.floor(pantry[0].stock / 2),
    status: 'pending',
    date: '2023-12-14',
  },
  {
    customer_id: customers[4].id,
    product_id: candy[0].id,
    quantity: Math.floor(candy[0].stock / 5),
    status: 'paid',
    date: '2024-02-29',
  },
  {
    customer_id: customers[3].id,
    product_id: beverages[0].id,
    quantity: Math.floor(beverages[0].stock / 6),
    status: 'paid',
    date: '2024-02-10',
  },
  {
    customer_id: customers[5].id,
    product_id: breakfast[0].id,
    quantity: Math.floor(breakfast[0].stock / 4),
    status: 'pending',
    date: '2024-05-05',
  },
  {
    customer_id: customers[7].id,
    product_id: meatAndSeafood[0].id,
    quantity: Math.floor(meatAndSeafood[0].stock / 2),
    status: 'pending',
    date: '2024-05-16',
  },
  {
    customer_id: customers[6].id,
    product_id: bakeryAndDessert[0].id,
    quantity: Math.floor(bakeryAndDessert[0].stock / 3),
    status: 'pending',
    date: '2023-06-27',
  },
  {
    customer_id: customers[3].id,
    product_id: organic[0].id,
    quantity: Math.floor(organic[0].stock / 1.5),
    status: 'paid',
    date: '2023-09-09',
  },
  {
    customer_id: customers[4].id,
    product_id: coffee[0].id,
    quantity: Math.floor(coffee[0].stock / 8),
    status: 'paid',
    date: '2024-06-17',
  },
  {
    customer_id: customers[5].id,
    product_id: deli[0].id,
    quantity: Math.floor(deli[0].stock / 6),
    status: 'paid',
    date: '2024-06-07',
  },
  {
    customer_id: customers[1].id,
    product_id: household[0].id,
    quantity: Math.floor(household[0].stock / 3),
    status: 'paid',
    date: '2024-04-19',
  },
  {
    customer_id: customers[5].id,
    product_id: floral[0].id,
    quantity: Math.floor(floral[0].stock / 2),
    status: 'paid',
    date: '2023-10-03',
  },
  {
    customer_id: customers[2].id,
    product_id: cleaning[0].id,
    quantity: Math.floor(cleaning[0].stock / 3),
    status: 'paid',
    date: '2023-08-18',
  },
  {
    customer_id: customers[0].id,
    product_id: floral[1].id,
    quantity: Math.floor(floral[1].stock / 7),
    status: 'paid',
    date: '2024-01-04',
  },
  {
    customer_id: customers[2].id,
    product_id: beverages[1].id,
    quantity: Math.floor(beverages[1].stock / 10),
    status: 'paid',
    date: '2024-03-05',
  },
  {
    customer_id: customers[3].id,
    product_id: cleaning[1].id,
    quantity: Math.floor(cleaning[1].stock / 7),
    status: 'paid',
    date: '2024-05-18',
  },
  {
    customer_id: customers[4].id,
    product_id: floral[2].id,
    quantity: Math.floor(floral[2].stock / 10),
    status: 'paid',
    date: '2023-11-04',
  },
  {
    customer_id: customers[5].id,
    product_id: beverages[3].id,
    quantity: Math.floor(beverages[3].stock / 4),
    status: 'paid',
    date: '2023-12-05',
  },
];

module.exports = {
  users,
  customers,
  orders,
};
